### ISSUE TITLE
Citation for GLM being SOTA?

### ISSUE THREAD

**Issue by kevinykuo** [kasaai/explain-ml-pricing#10]
Is it accurate to say GLM is state of the art for risk classification today? Are there sources we can/should cite or does it go without saying?
https://github.com/kasaai/explain-ml-pricing/blob/342628e1278c14e9321a1b0253526ffb7f9c64a5/manuscript/manuscript.Rmd#L34
@daniellupton?

**Comment by daniellupton** [comment]
I am not sure about that exact phrasing.

It's not really the most recent cutting-edge approach (it's been around for
30 years - they talk about that in the introductory section of the CAS
monograph on pricing with GLMs by Goldburd, Khare, Tevet
<https://www.casact.org/pubs/monographs/index.cfm?fa=goldburd-Khare-Tevet-monograph05>),
but it is the sort of "gold standard." I don't really have a reference for
that but I don't think it really needs to be supported by a reference - I
think we can claim that it's obvious.

I *guess *you could claim it's state-of-the-art? It's weird, because GLMs
have been around for a long time, and they're not the most advanced method
used in risk classification... but many (older) actuaries are still afraid
of them.

Might be better to refer to it as the gold standard, or the new standard,
or the current paradigm, or something like that?

**Comment by kevinykuo** [comment]
I like current paradigm/gold standard, will make change.
